<?

require "r/scripts.php";

if($_SERVER["SERVER_NAME"] != "localhost") $js = <<<HTML
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
HTML;
else $js = <<<HTML
<script type="text/javascript" src="jquery.js"></script>
HTML;

chdir("c");
ob_start();
$layout = "h";
$chapters = json_decode(file_get_contents("chapters.json"),true);
$pageNum = 0;
foreach($chapters as $chapter => $sections){
    $nav .= <<<HTML
    <tr class="head"><th colspan="2">$chapter</th></tr>
HTML;
    foreach($sections as $id => $title){
        $pageNum++;
        $pageId = $id;
        $pageDescription = $title;
        $oldPageTopic = $pageTopic;
        
        if(is_array($title)){
            $pageTopic = $title[0];
            $pageDescription = $title[1];
        }
        $colon = (empty($pageTopic) ? "" : ":");
        
        $pageOpen = <<<HTML
        
<div id="$pageId">

HTML;

        $pageNumber = <<<HTML

<a class="footer" href="?printable=$pageId"><span class="pagenum">$pageNum</span> <span class="chapter">$chapter</span></a>

HTML;
        
        $pageHeader = <<<HTML
        
<h2><a  href="index.phtml#$id"><!--<span>$pageTopic$colon</span> -->$pageDescription</a></h2>

HTML;
        include("$id.html");
        $pageContent = ob_get_contents();
        ob_clean();
        $pageClose = <<<HTML
        
</div>
<hr />

HTML;

        if($_GET["printable"] == $pageId){
            $content = $pageOpen . $pageHeader . $pageContent . $pageClose;
            $layout = "single";
        }else if($layout == "single"){
            continue(2);
        }else{
            $content .= $pageOpen . $pageNumber . $pageHeader . $pageContent . $pageClose;
            $nav .= <<<HTML

    <tr>
    <td class="num"><a href="#$pageId">$pageNum</a></td>
<!--    <td class="topic"><a href="#$pageId">$pageTopic&nbsp;</a></td>-->
    <td class="desc"><a href="#$pageId">$pageDescription</a></td>
    </tr>

HTML;

        }

    }
        
}
ob_end_clean();
chdir("..");

echo <<<HTML

<!DOCTYPE html>
<html class="$layout">
<head>
<meta charset="utf-8" />
<base target="_top" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Learn web design without a computer</title>
<link rel="stylesheet" href="indexcss.css" />
$js
<script type="text/javascript" src="indexjs.js"></script>
</head>
<body>

HTML;

if($layout != "single") echo <<<HTML

<div id="header">
<h1>Learn web design in two hours without a com&shy;puter</h1>
<p class="noprint"><button type="button" onclick="window.print();">Print all $pageNum pages!</button></p>
<p>Something confusing? Left out? Ugly?</p>
<p>E-mail me:</p>
<p><a href="mailto:hello@robertakarobin.com" target="_blank">hello&#64;robertakarobin&#46;com</a></p>
</div>

<div id="index">
<h2>Index</h2>
<table>

$nav

</table>
</div>

HTML;

echo <<<HTML

$content

</body>
</html>

HTML;
?>